name: repl
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - ipykernel
  - numpy
  - matplotlib
  - pyzmq
  - pyyaml
  - protobuf
  - flask
  - coverage
  - nbstripout
  - nbconvert
  - pip
  - pip:
    - protobuf3-to-dict
    - simple-pid
