# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circulo9_debug.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='circulo9_debug.proto',
  package='iit.advr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x63irculo9_debug.proto\x12\x08iit.advr\"\x9f\x05\n\x15\x63irculo9_debug_rx_pdo\x12\x12\n\nstatusword\x18\x01 \x01(\r\x12\x13\n\x0bmodes_of_op\x18\x02 \x01(\x05\x12\x18\n\x10pos_actual_value\x18\x03 \x01(\x05\x12\x18\n\x10vel_actual_value\x18\x04 \x01(\x05\x12\x19\n\x11\x63urr_actual_value\x18\x05 \x01(\x05\x12\x1b\n\x13torque_actual_value\x18\x06 \x01(\x05\x12\x0c\n\x04\x61in1\x18\x07 \x01(\r\x12\x0c\n\x04\x61in2\x18\x08 \x01(\r\x12\x14\n\x0c\x62rake_status\x18\t \x01(\r\x12\x17\n\x0fsafety_sw_byte1\x18\n \x01(\r\x12\x17\n\x0fsafety_sw_byte2\x18\x0b \x01(\r\x12\x17\n\x0fsafety_diag_in1\x18\x0c \x01(\x08\x12\x17\n\x0fsafety_diag_in2\x18\r \x01(\x08\x12\x10\n\x08\x65rr_code\x18\x0e \x01(\r\x12\x16\n\x0e\x64igital_inputs\x18\x0f \x01(\r\x12\x10\n\x08\x65nc1_raw\x18\x10 \x01(\r\x12\x10\n\x08\x65nc1_adj\x18\x11 \x01(\x05\x12\x10\n\x08\x65nc1_vel\x18\x12 \x01(\x05\x12\x10\n\x08\x65nc2_raw\x18\x13 \x01(\r\x12\x10\n\x08\x65nc2_adj\x18\x14 \x01(\x05\x12\x10\n\x08\x65nc2_vel\x18\x15 \x01(\x05\x12\x11\n\tuser_miso\x18\x16 \x01(\r\x12\x11\n\ttimestamp\x18\x17 \x01(\r\x12\x13\n\x0b\x63urr_demand\x18\x18 \x01(\x05\x12\x12\n\nvel_demand\x18\x19 \x01(\x05\x12\x12\n\npos_demand\x18\x1a \x01(\x05\x12\x15\n\rtorque_demand\x18\x1b \x01(\x05\x12\x16\n\x0e\x63ontrol_effort\x18\x1c \x01(\x05\x12\x18\n\x10\x63ore_temperature\x18\x1d \x01(\x05\x12\x19\n\x11\x64rive_temperature\x18\x1e \x01(\x05\"\x17\n\x15\x63irculo9_debug_tx_pdo')
)




_CIRCULO9_DEBUG_RX_PDO = _descriptor.Descriptor(
  name='circulo9_debug_rx_pdo',
  full_name='iit.advr.circulo9_debug_rx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusword', full_name='iit.advr.circulo9_debug_rx_pdo.statusword', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modes_of_op', full_name='iit.advr.circulo9_debug_rx_pdo.modes_of_op', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_actual_value', full_name='iit.advr.circulo9_debug_rx_pdo.pos_actual_value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_actual_value', full_name='iit.advr.circulo9_debug_rx_pdo.vel_actual_value', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curr_actual_value', full_name='iit.advr.circulo9_debug_rx_pdo.curr_actual_value', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque_actual_value', full_name='iit.advr.circulo9_debug_rx_pdo.torque_actual_value', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ain1', full_name='iit.advr.circulo9_debug_rx_pdo.ain1', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ain2', full_name='iit.advr.circulo9_debug_rx_pdo.ain2', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brake_status', full_name='iit.advr.circulo9_debug_rx_pdo.brake_status', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='safety_sw_byte1', full_name='iit.advr.circulo9_debug_rx_pdo.safety_sw_byte1', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='safety_sw_byte2', full_name='iit.advr.circulo9_debug_rx_pdo.safety_sw_byte2', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='safety_diag_in1', full_name='iit.advr.circulo9_debug_rx_pdo.safety_diag_in1', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='safety_diag_in2', full_name='iit.advr.circulo9_debug_rx_pdo.safety_diag_in2', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='iit.advr.circulo9_debug_rx_pdo.err_code', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='digital_inputs', full_name='iit.advr.circulo9_debug_rx_pdo.digital_inputs', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enc1_raw', full_name='iit.advr.circulo9_debug_rx_pdo.enc1_raw', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enc1_adj', full_name='iit.advr.circulo9_debug_rx_pdo.enc1_adj', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enc1_vel', full_name='iit.advr.circulo9_debug_rx_pdo.enc1_vel', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enc2_raw', full_name='iit.advr.circulo9_debug_rx_pdo.enc2_raw', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enc2_adj', full_name='iit.advr.circulo9_debug_rx_pdo.enc2_adj', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enc2_vel', full_name='iit.advr.circulo9_debug_rx_pdo.enc2_vel', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_miso', full_name='iit.advr.circulo9_debug_rx_pdo.user_miso', index=21,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='iit.advr.circulo9_debug_rx_pdo.timestamp', index=22,
      number=23, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curr_demand', full_name='iit.advr.circulo9_debug_rx_pdo.curr_demand', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_demand', full_name='iit.advr.circulo9_debug_rx_pdo.vel_demand', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_demand', full_name='iit.advr.circulo9_debug_rx_pdo.pos_demand', index=25,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque_demand', full_name='iit.advr.circulo9_debug_rx_pdo.torque_demand', index=26,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control_effort', full_name='iit.advr.circulo9_debug_rx_pdo.control_effort', index=27,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core_temperature', full_name='iit.advr.circulo9_debug_rx_pdo.core_temperature', index=28,
      number=29, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='drive_temperature', full_name='iit.advr.circulo9_debug_rx_pdo.drive_temperature', index=29,
      number=30, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=706,
)


_CIRCULO9_DEBUG_TX_PDO = _descriptor.Descriptor(
  name='circulo9_debug_tx_pdo',
  full_name='iit.advr.circulo9_debug_tx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=731,
)

DESCRIPTOR.message_types_by_name['circulo9_debug_rx_pdo'] = _CIRCULO9_DEBUG_RX_PDO
DESCRIPTOR.message_types_by_name['circulo9_debug_tx_pdo'] = _CIRCULO9_DEBUG_TX_PDO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

circulo9_debug_rx_pdo = _reflection.GeneratedProtocolMessageType('circulo9_debug_rx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _CIRCULO9_DEBUG_RX_PDO,
  __module__ = 'circulo9_debug_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.circulo9_debug_rx_pdo)
  ))
_sym_db.RegisterMessage(circulo9_debug_rx_pdo)

circulo9_debug_tx_pdo = _reflection.GeneratedProtocolMessageType('circulo9_debug_tx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _CIRCULO9_DEBUG_TX_PDO,
  __module__ = 'circulo9_debug_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.circulo9_debug_tx_pdo)
  ))
_sym_db.RegisterMessage(circulo9_debug_tx_pdo)


# @@protoc_insertion_point(module_scope)
