# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circulo9.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='circulo9.proto',
  package='iit.advr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63irculo9.proto\x12\x08iit.advr\"\xb0\x02\n\x0f\x63irculo9_rx_pdo\x12\x12\n\nstatusword\x18\x01 \x02(\r\x12\x13\n\x0bmodes_of_op\x18\x02 \x02(\x05\x12\x11\n\tmotor_pos\x18\x03 \x02(\x02\x12\x11\n\tmotor_vel\x18\x04 \x02(\x02\x12\x10\n\x08link_pos\x18\x05 \x02(\x02\x12\x10\n\x08link_vel\x18\x06 \x02(\x02\x12\x0f\n\x07\x63urrent\x18\x07 \x02(\x02\x12\x0e\n\x06torque\x18\x08 \x02(\x02\x12\x14\n\x0c\x64\x65manded_pos\x18\t \x01(\x02\x12\x14\n\x0c\x64\x65manded_vel\x18\n \x01(\x02\x12\x18\n\x10\x64\x65manded_current\x18\x0b \x01(\x02\x12\x17\n\x0f\x64\x65manded_torque\x18\x0c \x01(\x02\x12\x16\n\x0e\x63ontrol_effort\x18\r \x01(\x02\x12\x12\n\ndrive_temp\x18\x0e \x01(\x05\"\xb8\x01\n\x0f\x63irculo9_tx_pdo\x12\x15\n\rtarget_torque\x18\x01 \x02(\x02\x12\x12\n\ntarget_pos\x18\x02 \x02(\x02\x12\x12\n\ntarget_vel\x18\x03 \x02(\x02\x12\x16\n\x0etarget_current\x18\x04 \x02(\x02\x12\x0e\n\x06gain_0\x18\x05 \x01(\x02\x12\x0e\n\x06gain_1\x18\x06 \x01(\x02\x12\x0e\n\x06gain_2\x18\x07 \x01(\x02\x12\x0e\n\x06gain_3\x18\x08 \x01(\x02\x12\x0e\n\x06gain_4\x18\t \x01(\x02')
)




_CIRCULO9_RX_PDO = _descriptor.Descriptor(
  name='circulo9_rx_pdo',
  full_name='iit.advr.circulo9_rx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusword', full_name='iit.advr.circulo9_rx_pdo.statusword', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modes_of_op', full_name='iit.advr.circulo9_rx_pdo.modes_of_op', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor_pos', full_name='iit.advr.circulo9_rx_pdo.motor_pos', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor_vel', full_name='iit.advr.circulo9_rx_pdo.motor_vel', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link_pos', full_name='iit.advr.circulo9_rx_pdo.link_pos', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link_vel', full_name='iit.advr.circulo9_rx_pdo.link_vel', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current', full_name='iit.advr.circulo9_rx_pdo.current', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque', full_name='iit.advr.circulo9_rx_pdo.torque', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demanded_pos', full_name='iit.advr.circulo9_rx_pdo.demanded_pos', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demanded_vel', full_name='iit.advr.circulo9_rx_pdo.demanded_vel', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demanded_current', full_name='iit.advr.circulo9_rx_pdo.demanded_current', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demanded_torque', full_name='iit.advr.circulo9_rx_pdo.demanded_torque', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control_effort', full_name='iit.advr.circulo9_rx_pdo.control_effort', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='drive_temp', full_name='iit.advr.circulo9_rx_pdo.drive_temp', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=333,
)


_CIRCULO9_TX_PDO = _descriptor.Descriptor(
  name='circulo9_tx_pdo',
  full_name='iit.advr.circulo9_tx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_torque', full_name='iit.advr.circulo9_tx_pdo.target_torque', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_pos', full_name='iit.advr.circulo9_tx_pdo.target_pos', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_vel', full_name='iit.advr.circulo9_tx_pdo.target_vel', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_current', full_name='iit.advr.circulo9_tx_pdo.target_current', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain_0', full_name='iit.advr.circulo9_tx_pdo.gain_0', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain_1', full_name='iit.advr.circulo9_tx_pdo.gain_1', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain_2', full_name='iit.advr.circulo9_tx_pdo.gain_2', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain_3', full_name='iit.advr.circulo9_tx_pdo.gain_3', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain_4', full_name='iit.advr.circulo9_tx_pdo.gain_4', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=520,
)

DESCRIPTOR.message_types_by_name['circulo9_rx_pdo'] = _CIRCULO9_RX_PDO
DESCRIPTOR.message_types_by_name['circulo9_tx_pdo'] = _CIRCULO9_TX_PDO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

circulo9_rx_pdo = _reflection.GeneratedProtocolMessageType('circulo9_rx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _CIRCULO9_RX_PDO,
  __module__ = 'circulo9_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.circulo9_rx_pdo)
  ))
_sym_db.RegisterMessage(circulo9_rx_pdo)

circulo9_tx_pdo = _reflection.GeneratedProtocolMessageType('circulo9_tx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _CIRCULO9_TX_PDO,
  __module__ = 'circulo9_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.circulo9_tx_pdo)
  ))
_sym_db.RegisterMessage(circulo9_tx_pdo)


# @@protoc_insertion_point(module_scope)
