# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ft6_pdo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ft6_pdo.proto',
  package='iit.advr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rft6_pdo.proto\x12\x08iit.advr\"z\n\tFT_ati_rx\x12\x10\n\x08\x61\x66orce_x\x18\x01 \x02(\x02\x12\x10\n\x08\x61\x66orce_y\x18\x02 \x02(\x02\x12\x10\n\x08\x61\x66orce_z\x18\x03 \x02(\x02\x12\x11\n\tatorque_x\x18\x04 \x02(\x02\x12\x11\n\tatorque_y\x18\x05 \x02(\x02\x12\x11\n\tatorque_z\x18\x06 \x02(\x02\"9\n\nFT6_tx_pdo\x12\n\n\x02ts\x18\x01 \x02(\r\x12\x12\n\nop_idx_aux\x18\x02 \x01(\r\x12\x0b\n\x03\x61ux\x18\x03 \x01(\x02\"\xda\x01\n\nFT6_rx_pdo\x12\x0f\n\x07\x66orce_x\x18\x01 \x02(\x02\x12\x0f\n\x07\x66orce_y\x18\x02 \x02(\x02\x12\x0f\n\x07\x66orce_z\x18\x03 \x02(\x02\x12\x10\n\x08torque_x\x18\x04 \x02(\x02\x12\x10\n\x08torque_y\x18\x05 \x02(\x02\x12\x10\n\x08torque_z\x18\x06 \x02(\x02\x12\r\n\x05\x66\x61ult\x18\x07 \x01(\r\x12\x0b\n\x03rtt\x18\x08 \x01(\r\x12\x12\n\nop_idx_ack\x18\t \x01(\r\x12\x0b\n\x03\x61ux\x18\n \x01(\x02\x12&\n\tft_ati_rx\x18\x0b \x01(\x0b\x32\x13.iit.advr.FT_ati_rx')
)




_FT_ATI_RX = _descriptor.Descriptor(
  name='FT_ati_rx',
  full_name='iit.advr.FT_ati_rx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aforce_x', full_name='iit.advr.FT_ati_rx.aforce_x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aforce_y', full_name='iit.advr.FT_ati_rx.aforce_y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aforce_z', full_name='iit.advr.FT_ati_rx.aforce_z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='atorque_x', full_name='iit.advr.FT_ati_rx.atorque_x', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='atorque_y', full_name='iit.advr.FT_ati_rx.atorque_y', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='atorque_z', full_name='iit.advr.FT_ati_rx.atorque_z', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=149,
)


_FT6_TX_PDO = _descriptor.Descriptor(
  name='FT6_tx_pdo',
  full_name='iit.advr.FT6_tx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='iit.advr.FT6_tx_pdo.ts', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_idx_aux', full_name='iit.advr.FT6_tx_pdo.op_idx_aux', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aux', full_name='iit.advr.FT6_tx_pdo.aux', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=208,
)


_FT6_RX_PDO = _descriptor.Descriptor(
  name='FT6_rx_pdo',
  full_name='iit.advr.FT6_rx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='force_x', full_name='iit.advr.FT6_rx_pdo.force_x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force_y', full_name='iit.advr.FT6_rx_pdo.force_y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force_z', full_name='iit.advr.FT6_rx_pdo.force_z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque_x', full_name='iit.advr.FT6_rx_pdo.torque_x', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque_y', full_name='iit.advr.FT6_rx_pdo.torque_y', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque_z', full_name='iit.advr.FT6_rx_pdo.torque_z', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fault', full_name='iit.advr.FT6_rx_pdo.fault', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.FT6_rx_pdo.rtt', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_idx_ack', full_name='iit.advr.FT6_rx_pdo.op_idx_ack', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aux', full_name='iit.advr.FT6_rx_pdo.aux', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ft_ati_rx', full_name='iit.advr.FT6_rx_pdo.ft_ati_rx', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=429,
)

_FT6_RX_PDO.fields_by_name['ft_ati_rx'].message_type = _FT_ATI_RX
DESCRIPTOR.message_types_by_name['FT_ati_rx'] = _FT_ATI_RX
DESCRIPTOR.message_types_by_name['FT6_tx_pdo'] = _FT6_TX_PDO
DESCRIPTOR.message_types_by_name['FT6_rx_pdo'] = _FT6_RX_PDO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FT_ati_rx = _reflection.GeneratedProtocolMessageType('FT_ati_rx', (_message.Message,), dict(
  DESCRIPTOR = _FT_ATI_RX,
  __module__ = 'ft6_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.FT_ati_rx)
  ))
_sym_db.RegisterMessage(FT_ati_rx)

FT6_tx_pdo = _reflection.GeneratedProtocolMessageType('FT6_tx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _FT6_TX_PDO,
  __module__ = 'ft6_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.FT6_tx_pdo)
  ))
_sym_db.RegisterMessage(FT6_tx_pdo)

FT6_rx_pdo = _reflection.GeneratedProtocolMessageType('FT6_rx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _FT6_RX_PDO,
  __module__ = 'ft6_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.FT6_rx_pdo)
  ))
_sym_db.RegisterMessage(FT6_rx_pdo)


# @@protoc_insertion_point(module_scope)
