# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='generic.proto',
  package='iit.advr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rgeneric.proto\x12\x08iit.advr\"5\n\x05\x44ummy\x12\x0e\n\x06vect_f\x18\x01 \x03(\x02\x12\x0f\n\x07vect_ui\x18\x02 \x03(\r\x12\x0b\n\x03rtt\x18\x03 \x01(\r\"d\n\x0eGeneric_rx_pdo\x12\x0b\n\x03rtt\x18\x01 \x01(\r\x12\x12\n\nop_idx_ack\x18\x02 \x01(\r\x12\x0b\n\x03\x61ux\x18\x03 \x01(\x02\x12\x10\n\x08vect_int\x18\x04 \x03(\x03\x12\x12\n\nvect_float\x18\x05 \x03(\x02\"=\n\x0eGeneric_tx_pdo\x12\n\n\x02ts\x18\x01 \x01(\r\x12\x12\n\nop_idx_aux\x18\x02 \x01(\r\x12\x0b\n\x03\x61ux\x18\x03 \x01(\x02\"V\n\x0b\x43lient_pipe\x12(\n\x04type\x18\x01 \x02(\x0e\x32\x1a.iit.advr.Client_pipe.Type\"\x1d\n\x04Type\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\x08\n\x04QUIT\x10\x02')
)



_CLIENT_PIPE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='iit.advr.Client_pipe.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUIT', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=304,
  serialized_end=333,
)
_sym_db.RegisterEnumDescriptor(_CLIENT_PIPE_TYPE)


_DUMMY = _descriptor.Descriptor(
  name='Dummy',
  full_name='iit.advr.Dummy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vect_f', full_name='iit.advr.Dummy.vect_f', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vect_ui', full_name='iit.advr.Dummy.vect_ui', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.Dummy.rtt', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=80,
)


_GENERIC_RX_PDO = _descriptor.Descriptor(
  name='Generic_rx_pdo',
  full_name='iit.advr.Generic_rx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.Generic_rx_pdo.rtt', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_idx_ack', full_name='iit.advr.Generic_rx_pdo.op_idx_ack', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aux', full_name='iit.advr.Generic_rx_pdo.aux', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vect_int', full_name='iit.advr.Generic_rx_pdo.vect_int', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vect_float', full_name='iit.advr.Generic_rx_pdo.vect_float', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=182,
)


_GENERIC_TX_PDO = _descriptor.Descriptor(
  name='Generic_tx_pdo',
  full_name='iit.advr.Generic_tx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='iit.advr.Generic_tx_pdo.ts', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_idx_aux', full_name='iit.advr.Generic_tx_pdo.op_idx_aux', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aux', full_name='iit.advr.Generic_tx_pdo.aux', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=245,
)


_CLIENT_PIPE = _descriptor.Descriptor(
  name='Client_pipe',
  full_name='iit.advr.Client_pipe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='iit.advr.Client_pipe.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENT_PIPE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=333,
)

_CLIENT_PIPE.fields_by_name['type'].enum_type = _CLIENT_PIPE_TYPE
_CLIENT_PIPE_TYPE.containing_type = _CLIENT_PIPE
DESCRIPTOR.message_types_by_name['Dummy'] = _DUMMY
DESCRIPTOR.message_types_by_name['Generic_rx_pdo'] = _GENERIC_RX_PDO
DESCRIPTOR.message_types_by_name['Generic_tx_pdo'] = _GENERIC_TX_PDO
DESCRIPTOR.message_types_by_name['Client_pipe'] = _CLIENT_PIPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dummy = _reflection.GeneratedProtocolMessageType('Dummy', (_message.Message,), dict(
  DESCRIPTOR = _DUMMY,
  __module__ = 'generic_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.Dummy)
  ))
_sym_db.RegisterMessage(Dummy)

Generic_rx_pdo = _reflection.GeneratedProtocolMessageType('Generic_rx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _GENERIC_RX_PDO,
  __module__ = 'generic_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.Generic_rx_pdo)
  ))
_sym_db.RegisterMessage(Generic_rx_pdo)

Generic_tx_pdo = _reflection.GeneratedProtocolMessageType('Generic_tx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _GENERIC_TX_PDO,
  __module__ = 'generic_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.Generic_tx_pdo)
  ))
_sym_db.RegisterMessage(Generic_tx_pdo)

Client_pipe = _reflection.GeneratedProtocolMessageType('Client_pipe', (_message.Message,), dict(
  DESCRIPTOR = _CLIENT_PIPE,
  __module__ = 'generic_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.Client_pipe)
  ))
_sym_db.RegisterMessage(Client_pipe)


# @@protoc_insertion_point(module_scope)
