# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu_pdo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imu_pdo.proto',
  package='iit.advr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rimu_pdo.proto\x12\x08iit.advr\"\x80\x02\n\x0cImuVN_rx_pdo\x12\x0e\n\x06x_rate\x18\x01 \x02(\x02\x12\x0e\n\x06y_rate\x18\x02 \x02(\x02\x12\x0e\n\x06z_rate\x18\x03 \x02(\x02\x12\r\n\x05x_acc\x18\x04 \x02(\x02\x12\r\n\x05y_acc\x18\x05 \x02(\x02\x12\r\n\x05z_acc\x18\x06 \x02(\x02\x12\x0e\n\x06x_quat\x18\x07 \x01(\x02\x12\x0e\n\x06y_quat\x18\x08 \x01(\x02\x12\x0e\n\x06z_quat\x18\t \x01(\x02\x12\x0e\n\x06w_quat\x18\n \x01(\x02\x12\x0e\n\x06imu_ts\x18\x0b \x01(\r\x12\x13\n\x0btemperature\x18\x0c \x01(\r\x12\x12\n\ndigital_in\x18\r \x01(\r\x12\r\n\x05\x66\x61ult\x18\x0e \x01(\r\x12\x0b\n\x03rtt\x18\x0f \x01(\r')
)




_IMUVN_RX_PDO = _descriptor.Descriptor(
  name='ImuVN_rx_pdo',
  full_name='iit.advr.ImuVN_rx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_rate', full_name='iit.advr.ImuVN_rx_pdo.x_rate', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_rate', full_name='iit.advr.ImuVN_rx_pdo.y_rate', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_rate', full_name='iit.advr.ImuVN_rx_pdo.z_rate', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_acc', full_name='iit.advr.ImuVN_rx_pdo.x_acc', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_acc', full_name='iit.advr.ImuVN_rx_pdo.y_acc', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_acc', full_name='iit.advr.ImuVN_rx_pdo.z_acc', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_quat', full_name='iit.advr.ImuVN_rx_pdo.x_quat', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_quat', full_name='iit.advr.ImuVN_rx_pdo.y_quat', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_quat', full_name='iit.advr.ImuVN_rx_pdo.z_quat', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w_quat', full_name='iit.advr.ImuVN_rx_pdo.w_quat', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imu_ts', full_name='iit.advr.ImuVN_rx_pdo.imu_ts', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='iit.advr.ImuVN_rx_pdo.temperature', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='digital_in', full_name='iit.advr.ImuVN_rx_pdo.digital_in', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fault', full_name='iit.advr.ImuVN_rx_pdo.fault', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.ImuVN_rx_pdo.rtt', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=284,
)

DESCRIPTOR.message_types_by_name['ImuVN_rx_pdo'] = _IMUVN_RX_PDO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImuVN_rx_pdo = _reflection.GeneratedProtocolMessageType('ImuVN_rx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _IMUVN_RX_PDO,
  __module__ = 'imu_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.ImuVN_rx_pdo)
  ))
_sym_db.RegisterMessage(ImuVN_rx_pdo)


# @@protoc_insertion_point(module_scope)
