# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: power_pack_pdo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='power_pack_pdo.proto',
  package='iit.advr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x14power_pack_pdo.proto\x12\x08iit.advr\"5\n\x0fPowComan_tx_pdo\x12\x16\n\x0emaster_command\x18\x01 \x02(\r\x12\n\n\x02ts\x18\x02 \x02(\r\"S\n\x0fPowComan_rx_pdo\x12\x13\n\x0btemperature\x18\x01 \x02(\x02\x12\x0e\n\x06v_batt\x18\x02 \x02(\x02\x12\x0e\n\x06status\x18\x03 \x02(\r\x12\x0b\n\x03rtt\x18\x04 \x02(\r\"J\n\x11PowWalkman_tx_pdo\x12\x16\n\x0emaster_command\x18\x01 \x02(\r\x12\x11\n\tfault_ack\x18\x02 \x02(\r\x12\n\n\x02ts\x18\x03 \x02(\r\"\xa0\x01\n\x11PowWalkman_rx_pdo\x12\x0e\n\x06status\x18\x01 \x02(\r\x12\x13\n\x0btemperature\x18\x02 \x02(\r\x12\x11\n\tbatt_temp\x18\x03 \x02(\r\x12\x11\n\tbatt_volt\x18\x04 \x02(\r\x12\x11\n\tbatt_curr\x18\x05 \x02(\x05\x12\x11\n\tload_curr\x18\x06 \x02(\x05\x12\r\n\x05\x66\x61ult\x18\x07 \x02(\r\x12\x0b\n\x03rtt\x18\x08 \x02(\r\"^\n\x10PowF28M36_tx_pdo\x12\x16\n\x0emaster_command\x18\x01 \x02(\r\x12\x11\n\tfault_ack\x18\x02 \x02(\r\x12\x12\n\nop_idx_aux\x18\x03 \x01(\r\x12\x0b\n\x03\x61ux\x18\x04 \x01(\x02\"\xcb\x01\n\x10PowF28M36_rx_pdo\x12\x0e\n\x06v_batt\x18\x01 \x02(\x02\x12\x0e\n\x06v_load\x18\x02 \x02(\x02\x12\x0e\n\x06i_load\x18\x03 \x02(\x02\x12\x10\n\x08temp_pcb\x18\x04 \x02(\x02\x12\x15\n\rtemp_heatsink\x18\x05 \x02(\x02\x12\x11\n\ttemp_batt\x18\x06 \x02(\x02\x12\x0e\n\x06status\x18\x07 \x01(\r\x12\r\n\x05\x66\x61ult\x18\x08 \x01(\r\x12\x0b\n\x03rtt\x18\t \x01(\x02\x12\x12\n\nop_idx_ack\x18\n \x01(\r\x12\x0b\n\x03\x61ux\x18\x0b \x01(\x02')
)




_POWCOMAN_TX_PDO = _descriptor.Descriptor(
  name='PowComan_tx_pdo',
  full_name='iit.advr.PowComan_tx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='master_command', full_name='iit.advr.PowComan_tx_pdo.master_command', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='iit.advr.PowComan_tx_pdo.ts', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=87,
)


_POWCOMAN_RX_PDO = _descriptor.Descriptor(
  name='PowComan_rx_pdo',
  full_name='iit.advr.PowComan_rx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='iit.advr.PowComan_rx_pdo.temperature', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_batt', full_name='iit.advr.PowComan_rx_pdo.v_batt', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='iit.advr.PowComan_rx_pdo.status', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.PowComan_rx_pdo.rtt', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=172,
)


_POWWALKMAN_TX_PDO = _descriptor.Descriptor(
  name='PowWalkman_tx_pdo',
  full_name='iit.advr.PowWalkman_tx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='master_command', full_name='iit.advr.PowWalkman_tx_pdo.master_command', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fault_ack', full_name='iit.advr.PowWalkman_tx_pdo.fault_ack', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='iit.advr.PowWalkman_tx_pdo.ts', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=248,
)


_POWWALKMAN_RX_PDO = _descriptor.Descriptor(
  name='PowWalkman_rx_pdo',
  full_name='iit.advr.PowWalkman_rx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='iit.advr.PowWalkman_rx_pdo.status', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='iit.advr.PowWalkman_rx_pdo.temperature', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batt_temp', full_name='iit.advr.PowWalkman_rx_pdo.batt_temp', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batt_volt', full_name='iit.advr.PowWalkman_rx_pdo.batt_volt', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batt_curr', full_name='iit.advr.PowWalkman_rx_pdo.batt_curr', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load_curr', full_name='iit.advr.PowWalkman_rx_pdo.load_curr', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fault', full_name='iit.advr.PowWalkman_rx_pdo.fault', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.PowWalkman_rx_pdo.rtt', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=411,
)


_POWF28M36_TX_PDO = _descriptor.Descriptor(
  name='PowF28M36_tx_pdo',
  full_name='iit.advr.PowF28M36_tx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='master_command', full_name='iit.advr.PowF28M36_tx_pdo.master_command', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fault_ack', full_name='iit.advr.PowF28M36_tx_pdo.fault_ack', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_idx_aux', full_name='iit.advr.PowF28M36_tx_pdo.op_idx_aux', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aux', full_name='iit.advr.PowF28M36_tx_pdo.aux', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=507,
)


_POWF28M36_RX_PDO = _descriptor.Descriptor(
  name='PowF28M36_rx_pdo',
  full_name='iit.advr.PowF28M36_rx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v_batt', full_name='iit.advr.PowF28M36_rx_pdo.v_batt', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_load', full_name='iit.advr.PowF28M36_rx_pdo.v_load', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i_load', full_name='iit.advr.PowF28M36_rx_pdo.i_load', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp_pcb', full_name='iit.advr.PowF28M36_rx_pdo.temp_pcb', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp_heatsink', full_name='iit.advr.PowF28M36_rx_pdo.temp_heatsink', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp_batt', full_name='iit.advr.PowF28M36_rx_pdo.temp_batt', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='iit.advr.PowF28M36_rx_pdo.status', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fault', full_name='iit.advr.PowF28M36_rx_pdo.fault', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.PowF28M36_rx_pdo.rtt', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_idx_ack', full_name='iit.advr.PowF28M36_rx_pdo.op_idx_ack', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aux', full_name='iit.advr.PowF28M36_rx_pdo.aux', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=713,
)

DESCRIPTOR.message_types_by_name['PowComan_tx_pdo'] = _POWCOMAN_TX_PDO
DESCRIPTOR.message_types_by_name['PowComan_rx_pdo'] = _POWCOMAN_RX_PDO
DESCRIPTOR.message_types_by_name['PowWalkman_tx_pdo'] = _POWWALKMAN_TX_PDO
DESCRIPTOR.message_types_by_name['PowWalkman_rx_pdo'] = _POWWALKMAN_RX_PDO
DESCRIPTOR.message_types_by_name['PowF28M36_tx_pdo'] = _POWF28M36_TX_PDO
DESCRIPTOR.message_types_by_name['PowF28M36_rx_pdo'] = _POWF28M36_RX_PDO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowComan_tx_pdo = _reflection.GeneratedProtocolMessageType('PowComan_tx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _POWCOMAN_TX_PDO,
  __module__ = 'power_pack_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.PowComan_tx_pdo)
  ))
_sym_db.RegisterMessage(PowComan_tx_pdo)

PowComan_rx_pdo = _reflection.GeneratedProtocolMessageType('PowComan_rx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _POWCOMAN_RX_PDO,
  __module__ = 'power_pack_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.PowComan_rx_pdo)
  ))
_sym_db.RegisterMessage(PowComan_rx_pdo)

PowWalkman_tx_pdo = _reflection.GeneratedProtocolMessageType('PowWalkman_tx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _POWWALKMAN_TX_PDO,
  __module__ = 'power_pack_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.PowWalkman_tx_pdo)
  ))
_sym_db.RegisterMessage(PowWalkman_tx_pdo)

PowWalkman_rx_pdo = _reflection.GeneratedProtocolMessageType('PowWalkman_rx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _POWWALKMAN_RX_PDO,
  __module__ = 'power_pack_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.PowWalkman_rx_pdo)
  ))
_sym_db.RegisterMessage(PowWalkman_rx_pdo)

PowF28M36_tx_pdo = _reflection.GeneratedProtocolMessageType('PowF28M36_tx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _POWF28M36_TX_PDO,
  __module__ = 'power_pack_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.PowF28M36_tx_pdo)
  ))
_sym_db.RegisterMessage(PowF28M36_tx_pdo)

PowF28M36_rx_pdo = _reflection.GeneratedProtocolMessageType('PowF28M36_rx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _POWF28M36_RX_PDO,
  __module__ = 'power_pack_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.PowF28M36_rx_pdo)
  ))
_sym_db.RegisterMessage(PowF28M36_rx_pdo)


# @@protoc_insertion_point(module_scope)
