# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skin_sens_pdo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skin_sens_pdo.proto',
  package='iit.advr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13skin_sens_pdo.proto\x12\x08iit.advr\"\x19\n\x0bSkin_tx_pdo\x12\n\n\x02ts\x18\x01 \x02(\r\">\n\x0bSkin_rx_pdo\x12\r\n\x05\x66\x61ult\x18\x01 \x02(\r\x12\x0b\n\x03rtt\x18\x02 \x02(\r\x12\x13\n\x07\x66orceXY\x18\x03 \x03(\rB\x02\x10\x01')
)




_SKIN_TX_PDO = _descriptor.Descriptor(
  name='Skin_tx_pdo',
  full_name='iit.advr.Skin_tx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='iit.advr.Skin_tx_pdo.ts', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=58,
)


_SKIN_RX_PDO = _descriptor.Descriptor(
  name='Skin_rx_pdo',
  full_name='iit.advr.Skin_rx_pdo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fault', full_name='iit.advr.Skin_rx_pdo.fault', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='iit.advr.Skin_rx_pdo.rtt', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forceXY', full_name='iit.advr.Skin_rx_pdo.forceXY', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['Skin_tx_pdo'] = _SKIN_TX_PDO
DESCRIPTOR.message_types_by_name['Skin_rx_pdo'] = _SKIN_RX_PDO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Skin_tx_pdo = _reflection.GeneratedProtocolMessageType('Skin_tx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _SKIN_TX_PDO,
  __module__ = 'skin_sens_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.Skin_tx_pdo)
  ))
_sym_db.RegisterMessage(Skin_tx_pdo)

Skin_rx_pdo = _reflection.GeneratedProtocolMessageType('Skin_rx_pdo', (_message.Message,), dict(
  DESCRIPTOR = _SKIN_RX_PDO,
  __module__ = 'skin_sens_pdo_pb2'
  # @@protoc_insertion_point(class_scope:iit.advr.Skin_rx_pdo)
  ))
_sym_db.RegisterMessage(Skin_rx_pdo)


_SKIN_RX_PDO.fields_by_name['forceXY']._options = None
# @@protoc_insertion_point(module_scope)
